### ISSUE TITLE
AWS server-side error handling

### ISSUE THREAD

**Issue by laughedelic** [ohnosequences/loquat#49]
When there are a lot of workers milking the same SQS queue, at some point they get a lot of `Request limit exceeded. (Service: AmazonEC2; Status Code: 503` exceptions. Those should be caught and handled in the following way:

- [Error Retries and Exponential Backoff](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ErrorHandling.html#APIRetries)

**Comment by eparejatobes** [comment]
what's the connection with SQS?

**Comment by eparejatobes** [comment]
This should be about tagging a lot of instances at the same time, or something like it. It's about the EC2 API.

**Comment by laughedelic** [comment]
Here is a piece of log:

```
04:09:08.694 [main] INFO  ohnosequences.loquat.DataProcessor - Result was successful. deleting message from the input queue
04:09:10.890 [main] ERROR ohnosequences.loquat.DataProcessor - This instance will terminated due to a fatal error: Request limit exceeded. (Service: AmazonEC2; Status Code: 503; Error Code: RequestLimitExceeded; Request ID: 26b58877-1abb-4581-9572-64efdc5b2e48)
...
```

It always happens after successful processing of a task.

**Comment by eparejatobes** [comment]
but you change the state of the instance right? that idle, processing stuff :)

**Comment by laughedelic** [comment]
> what's the connection with SQS?

It's just about catching server-side exceptions and doing some retrying loop

**Comment by eparejatobes** [comment]
there you have it :+1:

**Comment by eparejatobes** [comment]
short tasks, much state changes, too idle/working

**Comment by eparejatobes** [comment]
we should only change the state like every min or so

**Comment by laughedelic** [comment]
Thanks for an idea, but I don't think it's the problem. Look at this piece of code:

```scala
      logger.info("Data processor is waiting for new data")
      instance.foreach(_.createTag(StatusTag.idle))
```

instance gets `idle` status when it starts waiting for the next task (after it finishes the current and will delete it from the queue, see the log above).
You see that there should be a log message before the state change.

**Comment by eparejatobes** [comment]
welcome to `Future`-land! :stuck_out_tongue:

**Comment by eparejatobes** [comment]
that error is about making a lot of requests to **EC2**, and that surely comes from having a lot of short tasks

**Comment by eparejatobes** [comment]
after skimming through the code, the quickest fix would be to disable this status update. The worker main processing loop should communicate with a different process which does the update (waiting x seconds before actually doing anything)

**Comment by laughedelic** [comment]
Wait, I don't see a lot of requests to EC2: workers are never idle in the blast case, they don't wait for tasks, they either get them from the first request (and then don't change the state) or they get this exception, because a lot of _different_ workers are querying the queue at the same time.

**Comment by eparejatobes** [comment]
The queue is totally unrelated with this, really. It's about EC2 requests.

**Comment by laughedelic** [comment]
Ok. This state thing is not needed for anything so I'll remove it for now and see if it helps.

**Comment by laughedelic** [comment]
Ok. After I removed any tagging from workers, this problem doesn't appear so far. But it's not related to https://github.com/ohnosequences/metagenomica/pull/48, I already got a couple of those fails.

**Comment by eparejatobes** [comment]
good!

**Comment by laughedelic** [comment]
I'm leaving this open though.

**Comment by laughedelic** [comment]
The failure from too often tagging was fixed, the `Request limit exceeded` exception regarding SQS polling is handled with the new version of aws-scala-tools (see #66).
