### ISSUE TITLE
Data flow diagram

### ISSUE THREAD

**Issue by laughedelic** [ohnosequences/loquat#63]
I was looking for web-apps to make an AWS data flow diagram for MG7 (https://github.com/ohnosequences/mg7/issues/91) and to try something first made a diagram for the Loquat architecture:

[![loquat2](https://cloud.githubusercontent.com/assets/766656/17685265/b7c70a1e-6362-11e6-9944-b7a511d469b0.png)](https://cloudcraft.co/view/afe9c8fb-e2c6-4a20-b64a-99eada98c796?key=EVOPt5rnPzba3T_XezTTxQ)

Here's a [link](https://cloudcraft.co/view/afe9c8fb-e2c6-4a20-b64a-99eada98c796?key=EVOPt5rnPzba3T_XezTTxQ) to the editable draft.

@ohnosequences/docs what do you think of such diagram in general and in the context of MG7?

**Comment by rtobes** [comment]
good!

**Comment by marina-manrique** [comment]
Super fine for me

**Comment by laughedelic** [comment]
Great. Is this particular diagram useful for the MG7 paper?

**Comment by rtobes** [comment]
Yes, I think so.
